// TermWise shared domain models. Ports of the SwiftUI domain types in
// `TermWise/Domain/PlanningTypes.swift`. Keep field names aligned with iOS + the
// future Node/Mongo backend so a JSON document round-trips between platforms.

export type TransactionType = 'expense' | 'income';

/// A single income/expense entry. `savedApplied` is money already covered by a
/// prior savings draw (subtracts from net expense, parity with iOS).
export interface TransactionItem {
  id: string;
  amount: number;
  name: string;
  category: string;
  note: string;
  /** ISO 8601 date string (matches iOS encoding). */
  date: string;
  /** ISO 8601 creation timestamp. */
  createdAt: string;
  type: TransactionType;
  /** Dollars previously parked in savings that this expense draws against. */
  savedApplied: number;
  /** Optional provenance flag (e.g. `markAsPaid`). */
  source?: string;
  /** Set when this row was generated by Mark-as-Paid for a fixed bill. */
  billId?: string;
  /** When true, the UI may offer Undo for this synthetic row. */
  undoable: boolean;
}

export type BudgetType = 'fixed' | 'variable' | 'savings';

export type PaymentFrequency = 'none' | 'monthly' | 'weekly' | 'biweekly' | 'oneTime';

/// A line on the Budget Plan screen. Fixed bills carry a `dueDay`; variable
/// items represent flexible spending categories (groceries, eating out, etc.).
export interface BudgetItem {
  id: string;
  category: string;
  planned: number;
  budgetType: BudgetType;
  frequency: PaymentFrequency;
  dueDay?: number;
  dueWeekday?: number;
  /** ISO 8601 for one-off / scheduled bills. */
  dueDate?: string;
  /** Optional user note (add flow / future edit). */
  memo?: string;
  /** Savings goals only: total target amount. */
  targetAmount?: number;
  /** Savings goals only: optional deadline (ISO 8601). */
  deadline?: string;
}

/// User-controlled budget configuration for a calendar month. Persisted per
/// `yyyy-MM` key.
export interface MonthlySettings {
  /** `yyyy-MM` key. */
  monthKey: string;
  /** When set, overrides "derived from income" Available to Budget. */
  availableToBudget?: number;
  /** Explicit dollar savings target override. Otherwise derive via rate. */
  customSavingsTarget?: number;
  /** Free-form per-month note. */
  monthlyNote?: string;
  /** Default 0.15 (15%). */
  desiredSavingsRate: number;
}

/// A specific savings goal (subset of `BudgetItem` with `budgetType === 'savings'`).
export interface SavingsGoal {
  id: string;
  name: string;
  targetAmount: number;
  currentSaved: number;
  deadline?: string;
}

/// Subset projection of a `BudgetItem` with `budgetType === 'fixed'`.
export interface RecurringBill {
  id: string;
  category: string;
  plannedAmount: number;
  dueDay?: number;
  frequency: PaymentFrequency;
  /** Computed: sum of expense transactions matching this bill this month. */
  actualPaid: number;
  /** Computed: paid / partial / unpaid label. */
  status: FixedBillStatus;
}

export type FixedBillStatus = 'paid' | 'partial' | 'unpaid';

/// Color palette tokens. Mirrors `CategoryPalette.swift`.
export type SpendingCategoryColor =
  | 'indigo'
  | 'green'
  | 'orange'
  | 'pink'
  | 'teal'
  | 'purple'
  | 'gray'
  | 'blue';

export interface SpendingCategory {
  /** Canonical display name. */
  name: string;
  type: BudgetType;
  color: SpendingCategoryColor;
}

/// Chart range presets — variable mode supports the full set; total mode
/// renders `month` only (matches the SwiftUI behavior).
export type ChartRange = 'sevenDays' | 'thirtyDays' | 'currentMonth';

export type ChartMode = 'variable' | 'total';

export type ThemePreference = 'system' | 'light' | 'dark';

export type SupportedCurrency = 'CAD' | 'USD' | 'EUR' | 'GBP';

export type BudgetWarningThresholdPercent = 75 | 90 | 100;

/// Local app preferences (Settings). Persisted with `PersistedState`.
export interface AppUserSettings {
  themePreference: ThemePreference;
  defaultCurrency: SupportedCurrency;
  /** Calendar day 1–28; only `1` is honored by budget logic today — see TODO in Settings UI. */
  monthStartDay: number;
  budgetWarningThresholdPercent: BudgetWarningThresholdPercent;
  billDueRemindersEnabled: boolean;
  budgetWarningRemindersEnabled: boolean;
  weeklySpendingSummaryEnabled: boolean;
}

export const DEFAULT_APP_USER_SETTINGS: AppUserSettings = {
  themePreference: 'system',
  defaultCurrency: 'USD',
  monthStartDay: 1,
  budgetWarningThresholdPercent: 90,
  billDueRemindersEnabled: false,
  budgetWarningRemindersEnabled: false,
  weeklySpendingSummaryEnabled: false
};

/// Reply to "Add this income to your budget?".
export type IncomePromptChoice = 'addToBudget' | 'keepAsReserve' | 'cancel';

/// Captured by Mark-as-Paid so Undo can restore the pre-payment state.
export interface PendingUndoBar {
  message: string;
  action: PendingUndoAction;
  /** Epoch ms when the snackbar was scheduled — used to auto-dismiss after 5s. */
  createdAt: number;
}

export type PendingUndoAction =
  | { kind: 'restoreRemovedTransaction'; transaction: TransactionItem }
  | { kind: 'undoMarkAsPaid'; billId: string; transactionId: string };

/// Income added via Quick Add — drives the "Add to budget?" prompt.
export interface PendingIncomePrompt {
  transactionId: string;
  amount: number;
  categoryName: string;
}

/// Snapshot persisted to AsyncStorage. Keep keys stable for forward compatibility.
export interface PersistedState {
  schemaVersion: 1;
  transactions: TransactionItem[];
  budgetItems: BudgetItem[];
  monthlySettingsByMonth: Record<string, MonthlySettings>;
  monthlyNotes: Record<string, string>;
  chartMode: ChartMode;
  variableChartRange: ChartRange;
  appUserSettings: AppUserSettings;
  /** First-run onboarding — false until the user finishes the intro flow. */
  hasCompletedOnboarding: boolean;
}
